AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  JumpCloudApiKey:
    Type: String
    NoEcho: true
    MinLength: 1
  CronExpression:
    Type: String
    Default: '0 0 * * ? *'  # Default to every day at midnight
    Description: Cron expression for the schedule (e.g., "0 0 * * ? *").
  OrganizationID:
    Type: String
    Default: ''
    Description: OPTIONAL - This parameter can be used to allow MTP Admins to select which Organization they would like to collect Directory Insights data for.
  Service:
    Type: String
    Default: "all"
    Description: 'Comma-delimited list of desired services to log. Available services: alerts, all, directory, ldap, mdm, object_storage, password_manager, radius, reports, saas_app_management, software, sso, systems, access_management . Default value is "all"'
  JsonFormat:
    Type: String
    AllowedValues:
      - MultiLine
      - SingleLine
    Default: MultiLine
    Description: 'JSon output indent format - MultiLine or SingleLine'

Metadata:
  AWS::ServerlessRepo::Application:
    Name: JumpCloud-DirectoryInsights
    Description: This Serverless Application can be used to collect your JumpCloud Directory Insights data at a regular interval.
    Author: JumpCloud Solutions Architecture
    SemanticVersion: 2.0.2
    HomePageUrl: https://git.io/JJlrZ
    SourceCodeUrl: https://git.io/JJiMo
    LicenseUrl: LICENSE

Resources:
  DirectoryInsightsRole:
    Type: AWS::IAM::Role
    Properties:
      Description: A role for use in the JumpCloud Directory Insights Serverless App
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      Policies:
        - PolicyName: CloudWatchMetrics
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudwatch:PutMetricData'
                Resource: '*'
  DirectoryInsightsBucket:
    Type: AWS::S3::Bucket
  DirectoryInsightsCmk:
    Type: AWS::KMS::Key
    Properties:
      Description: An Symmetric CMK for use in the JumpCloud Directory Insights Serverless App
      KeyPolicy:
        Version: '2012-10-17'
        Id: key-default-1
        Statement:
        - Sid: Enable IAM User Permissions
          Effect: Allow
          Principal:
            AWS: 
              Fn::Sub: arn:aws:iam::${AWS::AccountId}:root
          Action: kms:*
          Resource: '*'
        - Sid: Allow use of the key
          Effect: Allow
          Principal:
            AWS: !GetAtt [DirectoryInsightsRole, Arn]
          Action:
          - kms:DescribeKey
          - kms:Encrypt
          - kms:Decrypt
          - kms:ReEncrypt*
          - kms:GenerateDataKey
          - kms:GenerateDataKeyWithoutPlaintext
          Resource: '*'
  JcApiKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: JumpCloud API Key
      SecretString: !Ref JumpCloudApiKey
  JcApiResourcePolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref JcApiKey
      ResourcePolicy:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            AWS: !GetAtt DirectoryInsightsRole.Arn
          Action: secretsmanager:GetSecretValue
          Resource: "*"
  DirectoryInsightsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-jcdirectoryinsights.zip
      Handler: get-jcdirectoryinsights.jc_directoryinsights
      MemorySize: 512
      Timeout: 180
      Runtime: python3.9
      Role: !GetAtt DirectoryInsightsRole.Arn
      KmsKeyArn: !GetAtt DirectoryInsightsCmk.Arn
      Environment:
        Variables:
          JcApiKeyArn: !Ref JcApiKey
          CronExpression: !Ref CronExpression
          service: !Sub ${Service}
          BucketName: !Ref DirectoryInsightsBucket
          OrgId: !Sub ${OrganizationID}
          JsonFormat: !Sub ${JsonFormat}
      Events:
        ScheduleDirectoryInsightsTrigger:
          Type: Schedule
          Properties:
            Schedule: !Sub "cron(${CronExpression})"